// Country list for geo pricing (ISO-2 + name). CA-BC = British Columbia exception.
export const COUNTRIES = [
  { code: 'default', name: '🌐 Default (USD — all others)' },
  { code: 'CA-BC', name: '🇨🇦 Canada · British Columbia' },
  { code: 'US', name: '🇺🇸 United States' },
  { code: 'CA', name: '🇨🇦 Canada (rest)' },
  { code: 'GB', name: '🇬🇧 United Kingdom' },
  { code: 'AU', name: '🇦🇺 Australia' },
  { code: 'IN', name: '🇮🇳 India' },
  { code: 'AE', name: '🇦🇪 UAE' },
  { code: 'NZ', name: '🇳🇿 New Zealand' },
  { code: 'IE', name: '🇮🇪 Ireland' },
  { code: 'SG', name: '🇸🇬 Singapore' },
  { code: 'ZA', name: '🇿🇦 South Africa' },
  { code: 'DE', name: '🇩🇪 Germany' },
  { code: 'FR', name: '🇫🇷 France' },
  { code: 'ES', name: '🇪🇸 Spain' },
  { code: 'IT', name: '🇮🇹 Italy' },
  { code: 'NL', name: '🇳🇱 Netherlands' },
  { code: 'MX', name: '🇲🇽 Mexico' },
  { code: 'BR', name: '🇧🇷 Brazil' },
  { code: 'JP', name: '🇯🇵 Japan' },
  { code: 'PK', name: '🇵🇰 Pakistan' },
  { code: 'BD', name: '🇧🇩 Bangladesh' },
  { code: 'PH', name: '🇵🇭 Philippines' },
  { code: 'MY', name: '🇲🇾 Malaysia' },
  { code: 'SA', name: '🇸🇦 Saudi Arabia' },
  { code: 'KE', name: '🇰🇪 Kenya' },
  { code: 'NG', name: '🇳🇬 Nigeria' },
];
